

### CREAR NUEVO ESTUDIANTE
POST http://localhost:6945/v1/api/student
Content-Type: application/json

{
  "name": "Andrés",
  "lastName": "Duarte",
  "phone": "69987654"
}

### OBTENER TODOS LOS ESTUDIANTES
GET http://localhost:6945/v1/api/student/all
Accept: application/json

### OBTENER ESTUDIANTE POR ID
GET http://localhost:6945/v1/api/student/1
Accept: application/json