

### CREAR NUEVO ESTUDIANTE
POST http://localhost:6945/v1/api/student
Content-Type: application/json

{
  "name": "Camila",
  "lastName": "Mendoza",
  "phone": "69987654"
}

### OBTENER TODOS LOS ESTUDIANTES
GET http://192.168.1.14:8181/ms-student/v1/api/student/all
Accept: application/json

### OBTENER ESTUDIANTE POR ID
GET http://localhost:6945/v1/api/student/1
Accept: application/json


### CREAR NUEVO ESTUDIANTE POR GATEWAY
POST http://192.168.1.14:8181/ms-student/v1/api/student
Content-Type: application/json

{
  "name": "Mayra",
  "lastName": "Medina",
  "phone": "69961044"
}
